"""empty message

Revision ID: 2ec97501d1b9
Revises: 370c2c13bf67
Create Date: 2021-10-06 23:55:40.134669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec97501d1b9'
down_revision = '370c2c13bf67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image', sa.String(length=64), nullable=False))
    op.drop_column('users', 'profile_pics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pics', sa.VARCHAR(length=64), nullable=False))
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###
